=== Shadow13X/XML_Book_Library/xml/books.xsd
<?xml version="1.0"?>
<!--targetNamespace="library"-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="livre">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titre" type="xs:string" />
                            <xs:element name="auteurs">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="auteur" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nom" type="xs:string" />
                                                    <xs:element name="prenom" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="image"/>
                            <xs:element name="Paragraphe" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="information">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Language" type="xs:string" />
                            <xs:element name="Genre" type="xs:string" />
                            <xs:element name="Publisher" type="xs:string" />
                            <xs:element name="Pages" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="chapitres">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="chapitre" maxOccurs="unbounded">
                                <xs:complexType>                                    
                                    <xs:sequence>
                                        <xs:element name="paragraphes">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="paragraphe" type="xs:string" maxOccurs="unbounded" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="titre" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Shadow13X/XML_Book_Library/xml/livre2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl" ?>
<livre xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./books.xsd">
   <description>
      <titre> Nuit sombre et sacrée </titre>
      <auteurs>
         <nom>Connelly</nom>
         <prenom>Micheal</prenom>
      </auteurs> 
      <image   xlink:type="simple" xlink:href="https://images-eu.ssl-images-amazon.com/images/I/41A8OVKanIL._SX195_.jpg" >   
      </image>   
      <Paragraphe>
          «Spectaculaire. Nuit sombre et sacrée est un roman haletant et très, très sombre.»
          Washington Post
      </Paragraphe>
   </description>
   <information>
      <Language> Français</Language>
      <Genre>Crime &amp;  Thriller </Genre>
      <Publisher>  Calmann-Lévy </Publisher>
      <Pages> 432 </Pages>
   </information>
   <chapitres>
      <chapitre titre="Chapitre 1">
         <paragraphes>
            <paragraphe> 
            Les officiers de la patrouille avaient laissé la porte d’entrée ouverte. Ils croyaient lui avoir rendu service en aérant, mais cela constituait une violation du protocole de conservation des éléments de preuve de la scène de crime. 
            Des insectes auraient pu y aller et venir et de l’ADN de contact être altéré par une brise traversant la maison. Les odeurs étant de la matière particulaire, aérer une scène de crime, c’était en perdre des éléments.
            Mais les officiers de la patrouille ne savaient pas tout ça. Le rapport que Ballard avait reçu du lieutenant de veille disait que le corps se trouvait depuis deux ou trois jours dans une bâtisse fermée avec climatisation arrêtée. 
            À le citer, l’endroit puait aussi fort qu’un plein sac de mouffettes.
            </paragraphe>
            <paragraphe> 
            Là, devant elle, deux véhicules de patrouille stationnaient le long du trottoir. Trois hommes en bleu se tenaient debout à côté et l’attendaient. Ballard ne pensait pas vraiment qu’ils seraient restés à l’intérieur avec le corps.
            Cent mètres au-dessus dans les airs, un hélico décrivait des cercles, projecteur braqué sur la rue. 
            On aurait dit une laisse de lumière retenant l’appareil pour l’empêcher de disparaître au loin.
            Ballard coupa le moteur, mais resta un instant assise dans son véhicule de fonction. 
            Elle s’était garée devant un espace entre deux maisons et regarda la ville qui se répandait en un vaste tapis scintillant sous ses yeux. 
            Peu de gens se rendent compte qu’Hollywood Boulevard se perd haut dans les montagnes et, étroit et resserré, dessert alors un quartier strictement résidentiel, bien loin du mélange de clinquant et de crasse de La Mecque touristique qu’il est tout en bas, où les visiteurs posent avec des clodos en costume de super-héros et sur des étoiles gravées dans le trottoir. 
            Dans ses hauteurs, tout n’est qu’argent et pouvoir, et elle savait qu’un meurtre dans ces collines faisait toujours sortir les grands pontes. Elle ne faisait, elle, que du « baby-sitting » et ne garderait cette affaire que peu de temps. Celle-ci terminerait aux Homicides du West Bureau, voire à la division des Vols et Homicides du centre-ville, tout dépendant de l’identité de la victime et de son statut social.
            </paragraphe>
         </paragraphes>
      </chapitre>
   </chapitres> 
</livre>

=== Shadow13X/XML_Book_Library/xml/livre9.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl" ?>
<livre xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./books.xsd">
   <description>
      <titre> Les cicatrices </titre>
      <auteurs>
         <nom>Favan</nom>
         <prenom>Claire </prenom>
      </auteurs> 
      <image   xlink:type="simple" xlink:href="https://images-eu.ssl-images-amazon.com/images/I/51lW6azZiKL._SX195_.jpg" >   
      </image>   
      <Paragraphe>
            Un polar original et addictif.  » Le Parisien
            «  Machiavélique.  » Femme Actuelle
            «  Une romancière à suivre de près.  » CNEWS

      </Paragraphe>
   </description>
   <information>
      <Language> Français</Language>
      <Genre>Crime &amp; Thrillers</Genre>
      <Publisher> HarpercCollins </Publisher>
      <Pages> 368 </Pages>
   </information>
   <chapitres>
      <chapitre titre="">
         <paragraphes>
            <paragraphe> 
            Elle cligne des yeux plusieurs fois et porte la main gauche à son front. Un raclement suivi d’un tintement lui vrille le cerveau. Elle a la bouche pâteuse, sans compter ce putain de mal de crâne qui la fait grogner de douleur. Elle se sent aussi désorientée qu’un lendemain de cuite.
            Elle sait que c’est pitoyable de se réveiller chez quelqu’un dont elle ne se rappelle plus le prénom et d’avoir oublié les événements qui l’ont conduite jusque chez lui, pourtant ce n’est pas la première fois qu’elle échoue ainsi dans le lit d’un inconnu après une soirée bien arrosée, et ça ne sera pas la dernière.    
            </paragraphe>
            <paragraphe> 
            Il est sans doute temps de s’éclipser discrètement, avant que la scène devienne gênante. Elle tente de se redresser en poussant un gémissement. Son corps fait de la résistance. La vache ! Qu’est-ce qu’elle a foutu hier ? Elle a mal partout.
            Entre ses doigts qui massent ses tempes, elle observe le décor, et son cœur manque un battement. Son cerveau se remet instantanément à fonctionner. En mode panique.
            </paragraphe>
         </paragraphes>
      </chapitre>
   </chapitres> 
</livre>
