=== Shadow13X/XML_Book_Library/xml/books.xsd
<?xml version="1.0"?>
<!--targetNamespace="library"-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="livre">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titre" type="xs:string" />
                            <xs:element name="auteurs">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="auteur" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nom" type="xs:string" />
                                                    <xs:element name="prenom" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="image"/>
                            <xs:element name="Paragraphe" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="information">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Language" type="xs:string" />
                            <xs:element name="Genre" type="xs:string" />
                            <xs:element name="Publisher" type="xs:string" />
                            <xs:element name="Pages" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="chapitres">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="chapitre" maxOccurs="unbounded">
                                <xs:complexType>                                    
                                    <xs:sequence>
                                        <xs:element name="paragraphes">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="paragraphe" type="xs:string" maxOccurs="unbounded" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="titre" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Shadow13X/XML_Book_Library/xml/livre7.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl" ?>
<livre xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./books.xsd">
   <description>
      <titre> </titre>
      <auteurs>
         <nom>Agnès </nom>
         <prenom>Martin-Lugand</prenom>
      </auteurs> 
      <image  xlink:type="simple" xlink:href="https://static.fnac-static.com/multimedia/Images/FR/NR/c6/c2/b1/11649734/1540-1/tsp20200514070156/Nos-resiliences.jpg" >   
      </image>   
      <Paragraphe>
        Notre vie avait-elle irrémédiablement basculé ? Ne serait-elle plus jamais comme avant ? Étrange, cette notion d'avant et d'après. 
        Je sentais que nous venions de perdre quelque chose d'essentiel. Aucune projection dans l'avenir. 
        Aucun espoir. Rien. Le vide. Une ombre planait désormais sur notre vie. Et j'avais peur. Mais cette peur, je devais la canaliser, l'étouffer, l'éloigner, je ne pouvais me permettre de me laisser engloutir.
        Un seul instant suffit-il à faire basculer toute une vie ? 
      </Paragraphe>
   </description>
   <information>
      <Language> Français</Language>
      <Genre>Fiction &amp; Literature</Genre>
      <Publisher> Michel Lafon </Publisher>
      <Pages> 207 </Pages>
   </information>
   <chapitres>
      <chapitre titre="Chapitre 1">
         <paragraphes>
            <paragraphe> 
            Je me glissai seule dans notre lit pour la dernière fois avant longtemps. 
            J’aimais l’atmosphère de ces nuits-là. Un mélange d’impatience et de fébrilité. Une excitation à le retrouver. 
            Une appréhension qu’il vive mal son retour. Un goût d’euphorie qui submerge. Une envie d’accélérer le temps et de le ralentir à la fois, tant cette ultime attente était jouissive après un mois d’absence. 
            Dans la pénombre de notre chambre, j’avais une perception accrue des bruits de la maison ; le moindre craquement dans la toiture, le chant de la pluie, le moindre petit pas de l’un des enfants se levant avec la bonne excuse d’aller aux toilettes, Monsieur, notre chien, qui ne dormait que d’un œil en grognant dans son panier, Mademoiselle, notre vieille chatte, qui sautait de meuble en meuble.
            </paragraphe>
            <paragraphe> 
            Eux aussi attendaient son retour. Nos esprits à tous étaient tournés vers lui. 
            Il devait être en route à cette heure-ci. Il roulait vers chez lui, vers chez nous. 
            J’avais suivi l’atterrissage de son avion en direct sur mon téléphone. Il ne m’avait pas appelée. Il me disait toujours qu’il n’allait pas prendre le risque de me réveiller, alors qu’il rentrait dans quelques heures. 
            Il s’amusait à croire que je pouvais dormir profondément en attendant son retour. Je ne m’en offusquais pas, il avait besoin de ce temps en tête-à-tête avec lui-même pour se préparer à revenir parmi nous, pour se retrouver, pour se fondre à nouveau dans sa peau de mari et de père. 
            Non pas qu’il nous oubliât pendant ce voyage, mais il renouait avec celui qu’il était avant d’avoir une famille, du temps où il n’avait ni femme ni enfants.
            </paragraphe>
         </paragraphes>
      </chapitre>
   </chapitres> 
</livre>

=== Shadow13X/XML_Book_Library/xml/livre8.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl" ?>
<livre xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./books.xsd">
   <description>
      <titre> Celle qui pleurait sousl'eau</titre>
      <auteurs>
         <nom>Tackian</nom>
         <prenom>Niko</prenom>
      </auteurs> 
      <image   xlink:type="simple" xlink:href="https://www.babelio.com/couv/CVT_Celle-qui-pleurait-sous-leau_1993.jpg" >   
      </image>   
      <Paragraphe>
          SI CLARA N’AVAIT PAS AIMÉ CET HOMME, ELLE SERAIT TOUJOURS EN VIE.
      </Paragraphe>
   </description>
   <information>
      <Language>Français </Language>
      <Genre>Crime &amp; Thrillers </Genre>
      <Publisher>  Editions de l'épée</Publisher>
      <Pages> 270 </Pages>
   </information>
   <chapitres>
      <chapitre titre="Chapitre 1">
         <paragraphes>
            <paragraphe> 
            La nuit était chaude et aussi étouffante qu’un four. Mais Laurence et Sacha s’en foutaient bien. Ils avaient tout juste dix-sept ans, des rêves plein le crâne et l’envie de s’envoyer en l’air. 
            Un pote du lycée leur avait parlé d’une fenêtre qu’il suffisait de faire coulisser pour pénétrer dans la forteresse en briques rouges surplombant la butte. De toute façon l’alarme ne marchait plus depuis bien longtemps et, à cette heure tardive, ils ne risquaient certainement pas de croiser qui que ce soit. 
            Après être entrés dans le bâtiment, ils se déshabillèrent sur le bord du bassin et commencèrent à se bécoter dans l’obscurité. Puis Laurence se décida à plonger dans l’eau tiède et son mec ne traîna pas pour la rejoindre. Ils pouvaient deviner un vaste espace autour d’eux et une forme étrange qui se balançait dans les airs, mais ce n’étaient que des ombres imprécises à peine éclairées par la lueur jaunâtre des quelques loupiotes de sécurité. À ce moment précis, rien n’importait plus que leur désir. 
            Il la colla contre son corps pour qu’elle puisse bien sentir à quel point il avait envie d’elle, mais elle s’échappa en gloussant pour faire la course. C’est là que tout dérapa. Elle hurla d’abord de surprise, puis de dégoût et enfin son cri se transforma en une terreur primale. 
            Quelque chose flottait avec eux dans l’eau. C’était poisseux, c’était liquide, le visage de Laurence en était recouvert. Sacha eut le courage de se rapprocher, courage bien vite disparu au contact d’une chair froide et molle. Alors le désir s’évanouit comme la lumière d’une bougie soufflée par le vent et il eut une violente envie de vomir en tentant de rejoindre le bord. Et pendant qu’ils fuyaient la piscine en pleurant, le sang continua de se répandre dans l’eau du bassin, goutte après goutte…
            </paragraphe>
            <paragraphe> 
            Comme tous les dimanches matin depuis quinze jours, José s’était dépêché d’attraper le bus de la ligne 75 pour rejoindre son arrêt en bordure du parc des Buttes-Chaumont. 
            La piscine ouvrait à 7 heures, mais il lui fallait une bonne demi-heure pour faire son tour d’inspection. Ce mois de juillet parisien atteignait des chaleurs caniculaires et il appréciait particulièrement cette petite balade à la fraîche sur un bitume pas encore chauffé à blanc. 
            Et puis ça lui permettait de réfléchir et de classer ses idées… concernant Mathilde notamment. Ils étaient mariés depuis dix ans et élevaient deux beaux enfants, mais quelque chose clochait dans l’édifice de leur famille idéale. Quelque chose de bien pourri dont il devrait s’occuper, un jour, quand il aurait le courage d’affronter la réalité. 
            Après avoir remonté le long des grilles du parc, José avait bifurqué sur la gauche pour rejoindre la rue Jean-Ménans, puis sur la droite pour longer le vaste bâtiment en briques rouge vif qui abritait la piscine Pailleron. Il travaillait là 
            </paragraphe>
         </paragraphes>
      </chapitre>
   </chapitres> 
</livre>

=== Shadow13X/XML_Book_Library/xml/livre10.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl" ?>
<livre xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./books.xsd">
   <description>
      <titre> L'informateur </titre>
      <auteurs><auteur>
         <nom>Grisham</nom>
         <prenom>John</prenom>
      </auteur></auteurs> 
      <image   xlink:type="simple" xlink:href="https://www.babelio.com/couv/CVT_LInformateur_3249.jpg" >   
      </image>   
      <Paragraphe>
          Nous voulons tous que nos juges soient honnêtes et sages. C’est la première de nos attentes. 
          Leur intégrité, leur impartialité sont les fondements de notre système judiciaire. 
          Mais que se passe-t-il quand un juge ne respecte pas la loi, quand il se laisse corrompre ? 
          C’est rare, mais cela arrive.
      </Paragraphe>
   </description>
   <information>
      <Language> Français</Language>
      <Genre>Crime &amp; Thrillers</Genre>
      <Publisher>  JC Lattes</Publisher>
      <Pages> 520 </Pages>
   </information>
   <chapitres>
      <chapitre titre="Chapitre 1">
         <paragraphes>
            <paragraphe> 
            La radio diffusait du soft jazz. Un compromis. Lacy, la propriétaire de la Prius et donc de l’autoradio, détestait le rap presque autant que Hugo, son passager, détestait la country. 
            Ils n’avaient pu s’entendre sur rien, même en éliminant d’entrée le bluegrass. Causeries sur le sport, radio publique, vieux morceaux des années 1950, humoristes, BBC, CNN, opéras, ainsi qu’une centaine d’autres stations – rien ne leur convenait à tous les deux. 
            Ils avaient fini par jeter l’éponge et accepter le jazz d’ascenseur. L’une par lassitude morale, l’autre par lassitude physique. Juste un fond sonore, comme ça Hugo pourrait dormir, et elle ne pas être trop dérangée, parce que le jazz ce n’était vraiment pas son truc. 
            Encore un petit arrangement. Depuis toutes ces années qu’ils faisaient équipe, chacun avait appris à mettre de l’eau dans son vin. Il dormait, elle conduisait, et tout le monde était content.
            </paragraphe>
            <paragraphe>
            Avant la crise économique, les membres du Board on Judicial Conduct, le service de l’inspection judiciaire, avaient à leur disposition des Honda, des berlines, avec quatre portes, peinture blanche et peu de kilomètres. 
            Avec les restrictions budgétaires, cette petite flotte avait disparu. Lacy, Hugo, comme d’innombrables agents de la fonction publique en Floride, devaient désormais utiliser leur propre véhicule pour leur travail, dédommagés à vingt-cinq cents le kilomètre. 
            Hugo, avec quatre enfants et un emprunt pachydermique, avait une Bronco antédiluvienne qui parvenait tout juste à le conduire au bureau. Ils avaient donc pris la Prius de Lacy et Hugo dormait sur le siège côté passager. 
            </paragraphe>
         </paragraphes>
      </chapitre>
   </chapitres> 
</livre>

=== Shadow13X/XML_Book_Library/xml/livre6.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl" ?>
<livre xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./books.xsd">
   <description>
      <titre> Psychologie des Foules</titre>
      <auteurs>
         <nom>Le Bon</nom>
         <prenom>Gustave</prenom>
      </auteurs> 
      <image   xlink:type="simple" xlink:href="https://kbimages1-a.akamaihd.net/f44b7a65-31da-4596-823b-521a92dd9250/353/569/90/False/psychologie-des-foules-22.jpg" >   
      </image>   
      <Paragraphe>
          Écrit en 1895 par Gustave Le Bon (1841-1931), La psychologie des foules est un monument dans le domaine de la psychologie et reste une référence, un socle incontournable, 
          pour toute personne souhaitant comprendre ou "ressentir" l'âme des foules.
      </Paragraphe>
   </description>
   <information>
      <Language> Français</Language>
      <Genre>Psychologie</Genre>
      <Publisher> Public Domain </Publisher>
      <Pages> 209 </Pages>
   </information>
   <chapitres>
      <chapitre titre="Introduction">
         <paragraphes>
            <paragraphe> 
            Évolution de l'âge actuel.—Les grands changements de civilisation sont la conséquence de changements dans la pensée des peuples.—La croyance moderne à la puissance des foules.
            —Elle transforme la politique traditionnelle des États.—Comment se produit l'avènement des classes populaires et comment s'exerce leur puissance.
            —Conséquences nécessaires de la puissance des foules.—Elles ne peuvent exercer qu'un rôle destructeur.—C'est par elles que s'achève la dissolution des civilisations devenues trop vieilles.—Ignorance générale de la psychologie des foules.
            —Importance de l'étude des foules pour les législateurs et les hommes d'État.
            </paragraphe>
            <paragraphe>
            Les grands bouleversements qui précèdent les changements de civilisations, tels que la chute de l'Empire romain et la fondation de l'Empire arabe par exemple semblent, au premier abord, déterminés surtout par des transformations politiques considérables: invasions de peuples ou renversements de dynasties. 
            Mais une étude plus attentive de ces événements montre que, derrière leurs causes apparentes, se trouve le plus souvent, comme cause réelle, une modification profonde dans les idées des peuples. Les véritables bouleversements historiques ne sont pas ceux qui nous étonnent par leur grandeur et leur violence. 
            </paragraphe>
         </paragraphes>
      </chapitre>
   </chapitres> 
</livre>

=== Shadow13X/XML_Book_Library/xml/livre1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl" ?>
<livre xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./books.xsd">
   <description>
      <titre> La vie est un roman</titre>
      <auteurs>
         <nom> Musso</nom>
         <prenom>Guillaume </prenom>
      </auteurs> 
      <image   xlink:type="simple" xlink:href="https://www.guillaumemusso.com/sites/default/files/images/livres/couv/9782702165546-001-T.jpeg" >   
      </image>   
      <Paragraphe>
            POUR LUI, TOUT EST ÉCRIT D'AVANCE
               POUR ELLE TOUT RESTE À ÉCRIRE
            « Un jour d’avril, ma fille de trois ans, Carrie, a disparu alors que nous jouions toutes les deux à cache-cache dans mon appartement de Brooklyn. »
            Au même moment, de l’autre côté de l’Atlantique, un écrivain au cœur broyé se terre dans une maison délabrée.
            Lui seul détient la clé du mystère. 
      </Paragraphe>
   </description>
   <information>
      <Language> Français</Language>
      <Genre>Fiction &amp; Literature </Genre>
      <Publisher> Calmann-Lévy </Publisher>
      <Pages> 304 </Pages>
   </information>
   <chapitres>
      <chapitre titre="Cachée">
         <paragraphes>
            <paragraphe> 
            Brooklyn, automne 2010
            Il y a six mois, le 12 avril 2010, ma fille de trois ans, Carrie Conway, m’a été enlevée alors que nous jouions toutes les deux à cache-cache dans mon appartement de Williamsburg.
            C’était un bel après-midi, clair et ensoleillé, comme New York en offre beaucoup au printemps. Fidèle à mes habitudes, j’étais allée à pied chercher Carrie à son école, la Montessori School de McCarren Park. 
            Sur le chemin du retour, nous nous étions arrêtées chez Marcello’s pour acheter une compote et un cannoli au citron que Carrie avait dévorés tout en gambadant gaiement à côté de sa poussette.
            </paragraphe>
            <paragraphe> 
            À notre arrivée chez nous, dans le lobby du Lancaster Building, au numéro 396 de Berry Street, notre nouveau gardien, Trevor Fuller Jones – 
            il avait été embauché moins de trois semaines auparavant –, a donné à Carrie une sucette au miel et au sésame en lui faisant promettre de ne pas la manger tout de suite. 
            Puis il lui a dit combien elle était chanceuse d’avoir une maman romancière, car elle devait lui raconter de belles histoires le soir dans son lit. 
            Je lui ai fait remarquer en riant que, pour dire une chose pareille, il n’avait dû ouvrir aucun de mes romans, ce dont il a convenu. 
            </paragraphe>
         </paragraphes>
      </chapitre>
   </chapitres> 
</livre>

=== Shadow13X/XML_Book_Library/xml/livre4.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl" ?>
<livre xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./books.xsd">
   <description>
      <titre> Quelqu'un de Bien </titre>
      <auteurs>
         <nom>Bourdine</nom>
         <prenom>Françoise</prenom>
      </auteurs> 
      <image   xlink:type="simple" xlink:href="https://www.lisez.com/includes/ajax_imatges.php?id=9782714481375" >   
      </image>   
      <Paragraphe>
          Faire face à l’adversité et se prouver qu’on est quelqu’un de bien.
      </Paragraphe>
   </description>
   <information>
      <Language> Français</Language>
      <Genre>Fiction &amp; Literature </Genre>
      <Publisher> Belfond </Publisher>
      <Pages> 198 </Pages>
   </information>
   <chapitres>
      <chapitre titre="CHAPITRE 1">
         <paragraphes>
            <paragraphe> 
            — Si quelqu’un peut vous conduire à la pharmacie de garde, à Cavaillon, je préférerais que vous commenciez votre traitement sans attendre.
            Caroline signa l’ordonnance qu’elle relut d’un coup d’œil avant de la tendre à son patient, un vieux monsieur qu’elle suivait régulièrement pour de multiples pathologies. Cependant, au-delà de ses problèmes de santé, il venait aussi chercher auprès de son médecin une oreille attentive et quelques mots d’encouragement. 
            Caroline était-elle encore capable de les lui offrir ? Fatiguée par une interminable journée de travail, elle se leva néanmoins pour le raccompagner jusqu’à la porte donnant sur la ruelle. On pouvait ainsi quitter son cabinet sans repasser par le secrétariat ou la salle d’attente, et ne pas montrer ses larmes quand on venait d’apprendre une mauvaise nouvelle.
            — Prenez soin de vous, dit-elle en lui serrant la main.
            </paragraphe>
            <paragraphe> 
            Elle n’utilisait jamais l’expression « Bon courage », une formule qu’elle jugeait trop angoissante. Puis elle gagna l’entrée où se tenait Diane, sa sœur, encore installée derrière son petit bureau.
            — Dis-moi qu’il n’y a plus personne…, s’enquit-elle d’un ton plein d’espoir.
            — Non, c’est fini, je viens de verrouiller.
            Diane ajouta, désignant la pendule accrochée en évidence sur l’un des murs :
            — À cette heure-ci, je considère que ta journée est terminée. Et je peux t’annoncer que tu as assuré quarante-neuf consultations !
            Ce qui n’était même pas un record. Caroline lâcha un soupir de soulagement et alla éteindre la lumière dans la salle d’attente où des magazines s’éparpillaient sur toutes les chaises. 
            Chaque matin, à sept heures, la femme de ménage venait mettre de l’ordre, aérait, lavait les sols, et le cabinet médical 
            </paragraphe>
         </paragraphes>
      </chapitre>
   </chapitres> 
</livre>

=== Shadow13X/XML_Book_Library/xml/livre5.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl" ?>
<livre xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./books.xsd">
   <description>
      <titre> Jeux Dangeureux </titre>
      <auteurs>
         <nom>Steel</nom>
         <prenom>Danielle</prenom>
      </auteurs> 
      <image   xlink:type="simple" xlink:href="https://www.lisez.com/includes/ajax_imatges.php?id=9782258191693" >   
      </image>   
      <Paragraphe>
          Peu importe les risques. Elle fera tout pour révéler la vérité.
      </Paragraphe>
   </description>
   <information>
      <Language>Français </Language>
      <Genre>Romance</Genre>
      <Publisher> Presses de la Cité </Publisher>
      <Pages> 242</Pages>
   </information>
   <chapitres>
      <chapitre titre="Chapitre 1">
         <paragraphes>
            <paragraphe> 
            Il était presque 4 heures du matin quand des coups de feu éclatèrent et qu’Alix Phillips courut se mettre à l’abri. 
            Une fabrique de conserves de fruits avait fermé en Alabama, mettant des milliers de gens sur le carreau. Le syndicat tentait depuis des mois d’empêcher la liquidation de l’entreprise, mais le désespoir et la frustration avaient fini par céder la place à la violence. 
            La plupart des ouvriers de l’usine étaient afro-américains, et certaines familles travaillaient là depuis plusieurs générations. Toute la nuit, la ville et ses environs avaient été livrés au pillage et à la destruction, et deux jeunes gens avaient été tués. Les unités antiémeute des cités voisines avaient été appelées à la rescousse, et l’odeur âcre du gaz lacrymogène flottait dans l’air. 
            Alix était en plein reportage en direct. Ben Chapman, son caméraman, l’attrapa brutalement par le bras pour l’obliger à partir, la forçant à abandonner son poste. Il dut presque la traîner pour la sortir de là. Les forces armées s’approchaient de la zone, et les fenêtres d’un bâtiment incendié par les pillards explosaient sous l’effet de la chaleur. 
            Alix venait juste d’annoncer sur une chaîne nationale qu’on n’avait rien vu de tel depuis les émeutes de Los Angeles en 1992.
            </paragraphe>
            <paragraphe> 
            — T’es complètement folle ou quoi ? cria Chapman, furieux, quand ils se réfugièrent derrière un bâtiment au bout de la rue.
            Des membres de la garde nationale et de la police anti-émeute passèrent près d’eux dans un bruit de tonnerre. Cela faisait une semaine que Ben et Alix se trouvaient sur les lieux. Alix, sa carte de presse autour du cou, avait le visage couvert de suie, et les yeux irrités par l’épais nuage de lacrymo.
            — T’as vraiment envie de te prendre une balle ?
            </paragraphe>
         </paragraphes>
      </chapitre>
   </chapitres> 
</livre>

=== Shadow13X/XML_Book_Library/xml/livre3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl" ?>
<livre xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./books.xsd">
   <description>
      <titre> Le Meilleur des mondes </titre>
      <auteurs>
         <nom>Huxley </nom>
         <prenom>Aldous </prenom>
      </auteurs> 
      <image   xlink:type="simple" xlink:href="https://static.fnac-static.com/multimedia/Images/FR/NR/db/20/49/4792539/1540-1/tsp20130514171142/Le-meilleur-des-mondes.jpg" >   
      </image>   
      <Paragraphe>
            632 après Ford : désormais on compte les années à partir de l’invention de la voiture à moteur.
            La technologie et la science ont remplacé la liberté et Dieu.
      </Paragraphe>
   </description>
   <information>
      <Language> Français</Language>
      <Genre>Fiction &amp; Fantasy </Genre>
      <Publisher>  PLon</Publisher>
      <Pages>  234</Pages>
   </information>
   <chapitres>
      <chapitre titre="Chapitre 1">
         <paragraphes>
            <paragraphe> 
            Un bâtiment gris et trapu de trente-quatre étages seulement. Au-dessus de l’entrée principale, les mots : CENTRE D’INCUBATION ET DE CONDITIONNEMENT DE LONDRES-CENTRAL, et, dans un écusson, la devise de l’État mondial : COMMUNAUTÉ, IDENTITÉ, STABILITÉ.
            L’énorme pièce du rez-de-chaussée était exposée au nord. En dépit de l’été qui régnait au-delà des vitres, en dépit de toute la chaleur tropicale de la pièce elle-même, ce n’étaient que de maigres rayons d’une lumière crue et froide qui se déversaient par les fenêtres. 
            Les blouses des travailleurs étaient blanches, leurs mains, gantées de caoutchouc pâle, de teinte cadavérique. La lumière était gelée, morte, fantomatique. Ce n’est qu’aux cylindres jaunes des microscopes qu’elle empruntait un peu de substance riche et vivante, étendue le long des tubes comme du beurre.
             — Et ceci, dit le Directeur, ouvrant la porte, c’est la Salle de Fécondation.
            </paragraphe>
            <paragraphe> 
            Au moment où le Directeur de l’Incubation et du Conditionnement entra dans la pièce, trois cents Fécondateurs, penchés sur leurs instruments, étaient plongés dans ce silence où l’on ose à peine respirer, dans ce chantonnement ou ce sifflotement inconscient, par quoi se traduit la concentration la plus profonde. 
            Une bande d’étudiants nouvellement arrivés, très jeunes, roses et imberbes, se pressaient, pénétrés d’une certaine appréhension, voire de quelque humilité, sur les talons du Directeur. 
            Chacun d’eux portait un cahier de notes, dans lequel, chaque fois que le grand homme parlait, il griffonnait désespérément. Ils puisaient ici leur savoir à la source même. C’était un privilège rare. 
            Le D.I.C. de Londres-Central s’attachait toujours à faire faire à ses nouveaux étudiants, sous sa conduite-personnelle, le tour des divers services.
            </paragraphe>
         </paragraphes>
      </chapitre>
   </chapitres> 
</livre>
